spring:
  datasource:
    url: "${LIVINGHUB_LOCAL_DB_URL}"
    username: "${LIVINGHUB_LOCAL_DB_USERNAME}"
    password: "${LIVINGHUB_LOCAL_DB_PASSWORD}"
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
