CREATE TABLE identity_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_identity_users_username UNIQUE (username),
    CONSTRAINT ck_identity_users_username_format
        CHECK (username ~ '^[a-z][a-z0-9_]{2,29}$'),
    CONSTRAINT ck_identity_users_password_hash_not_blank
        CHECK (btrim(password_hash) <> '')
);
